runtime: php72
handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: .*
  script: auto
runtime_config:
    document_root: .
env_variables:
    APP_LOG: errorlog
    GOOGLE_STORAGE_BUCKET: clinical-276401.appspot.com
    MYSQL_USER: root
    MYSQL_PASSWORD: root
beta_settings:
    cloud_sql_instances: clinical-276401:us-central1:myinstance